Updated exponential model
rich-payne/dreamer pull request #42
Opened 2023-12-22 20:49 UTC by mitchell-thomann

Updated exponential model - including:

- Updated parameterization to match DoseFinding package
- Included upper bound on truncated prior to be user specified in case of sampling errors
- Updated documentation with new parameterization and truncated prior

2024-02-22 19:27 UTC, rich-payne requested changes
Right now the PR is incomplete for the pr_med() etc. functions.  However, if we plan to deprecate, this won't matter.

2024-02-22 19:27 UTC, rich-payne commented on R/model.R
> +#'   \deqn{y \sim N(f(d), \sigma^2)}
This is a binary function, so needs to retain the binomial likelihood and description.

2024-04-01 17:15 UTC, rich-payne requested changes
Looking good overall.  Thank you!

A few things that I've noted in comments which need addressing.  Once addressed, please open a new PR to request a merge into the "version4" branch rather than the main branch.    We can then place all the major updates on that branch.

Please record the changes which are made in this PR into the News file.

Lastly, I think we'll need to include some warnings/deprecations on the exponential and emax models about the changes.  There are some nice functions which the tidyverse supports it.  I will see if I can find a link to them and open a new issue.

2024-04-01 17:15 UTC, rich-payne commented on R/model.R
> +  bound = 10,
How universally applicable will this bound be?  We don't specify any other hyperparameters.  For consistency, should we omit a default argument?

2024-04-01 17:15 UTC, rich-payne commented on inst/jags/likelihood_emax_binary.jags
> + # LINK(f[i]) <- (ifelse(dose[i] == 0, a + b1 * (LONGITUDINAL), a + (b1 + (b2 - b1) / (exp # (b4 * (b3 - log(dose[i]))) + 1)) * (LONGITUDINAL)))
Remove commented code

2024-04-01 17:15 UTC, rich-payne commented on inst/jags/likelihood_exp.jags
> +  #f_sufficient[i] <- a + (b1 + b2 * (1 - exp(- b3 * dose_sufficient[i]))) * (LONGITUDINAL)
Remove commented code.

2024-04-01 17:26 UTC, rich-payne commented
We can use a call to `rlang::warn()` and `rlang::inform()` with the `.frequency` argument to display messages once per session or once every 8 hours to let users know about the update to the models.  This should probably be within the "model" functions directly.

2024-04-01 19:29 UTC, mitchell-thomann commented
Updated in new pull request

2024-04-01 19:29 UTC, closed without merging