Updates to EMAX and exponential models
rich-payne/dreamer pull request #46
Opened 2024-04-01 19:28 UTC by mitchell-thomann

Updated parameters for EMAX and exponential models including:

- JAGS code
- Documentation
- Posterior test cases
- Inform messages in model.R

2024-04-02 16:44 UTC, rich-payne requested changes
Thank you for the updates!  Just a few more minor comments.

2024-04-02 16:44 UTC, rich-payne commented on R/dreamer_mean.R
> +  #b1 + b2 * (1 - exp(- b3 * dose))
remove commented code

2024-04-02 16:44 UTC, rich-payne commented on R/model.R
> +  rlang::inform("Note updated EMAX model parameterization",
Can we update this message to something like "EMAX model parameterization has changed in dreamer version 4.   Please review the new model parameterization and update prior hyperparameters accordingly."

2024-04-02 16:44 UTC, rich-payne commented on R/model.R
> +  rlang::inform("Note updated exponential model parameterization",
Update message similar to the EMAX one suggested.

2024-04-02 16:44 UTC, rich-payne commented on R/model.R
> +  rlang::inform("Note updated EMAX model parameterization",
Update message as suggested in the continuous EMAX model comment.

2024-04-02 16:44 UTC, rich-payne commented on R/model.R
> +#'   \deqn{y \sim N(f(d), \sigma^2)}
This is incorrect -- we have a binary outcome so the likelihood is binomial.  Please revert.

2024-04-02 16:44 UTC, rich-payne commented on R/model.R
> +#'   \deqn{f(d) = b_1 + b_2 * (exp(d / b_3) - 1)}
Please add link back in since this is a binary endpoint.

2024-04-02 16:44 UTC, rich-payne commented on R/model.R
> +  rlang::inform("Note updated exponential model parameterization",
Please update message similar to that of the suggested EMAX model in other comment.

2024-04-18 20:28 UTC, mitchell-thomann commented
Requested changes complete

2024-05-16 17:44 UTC, rich-payne approved these changes
Looks great! Thanks!

2024-05-16 17:44 UTC, merged